version: '3.1'

services:

    database:
        image: mysql/mysql-server:5.7.9
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: api_noticias
            MYSQL_USER: lumen
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"

    mailhog:
        image: mailhog/mailhog:latest
        hostname: mailhog
        ports:
            - "8025:8025"